CREATE DATABASE Polygin;

USE Polygin;

CREATE TABLE Users(
Phone NVARCHAR(20) PRIMARY KEY NOT NULL,
[Password] NVARCHAR(50) NOT NULL,
FullName NVARCHAR(50) NOT NULL,
Sex BIT NULL,
[Address] NVARCHAR(50) NOT NULL,
Avatar NVARCHAR(50) NULL
)

CREATE TABLE [Roles](
Id VARCHAR(10) PRIMARY KEY NOT NULL,
[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Authorities(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
U_Phone NVARCHAR(20),
R_Id VARCHAR(10),
CONSTRAINT fk_ath_user FOREIGN KEY (U_Phone) REFERENCES Users (Phone),
CONSTRAINT fk_ath_role FOREIGN KEY (R_Id) REFERENCES [Roles] (Id)
)

CREATE TABLE Categories(
Id NVARCHAR(10) PRIMARY KEY NOT NULL,
Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Products(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] NVARCHAR(50) NOT NULL,
Price FLOAT NOT NULL,
Cate_Id NVARCHAR(10) NOT NULL,
[Description] NVARCHAR(max) Null,
[Status] BIT NOT NULL,
Quantity INT DEFAULT(1) NOT NULL,
CONSTRAINT fk_pdc_cate FOREIGN KEY (Cate_Id) REFERENCES Categories (Id)
)

CREATE TABLE [Images](
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Pdc_Id INT NOT NULL,
[image] NVARCHAR(30) NOT NULL,
CONSTRAINT fk_img_pdc FOREIGN KEY (Pdc_Id) REFERENCES Products (Id)
)

CREATE TABLE [Orders](
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CreateDate DATE NOT NULL,
[Address] NVARCHAR(MAX) NOT NULL,
U_Phone NVARCHAR(20) NOT NULL,
[Status] INT NOT NULL,
CONSTRAINT fk_ord_user FOREIGN KEY (U_Phone) REFERENCES Users (Phone)
)

CREATE TABLE OrderDetails(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Pdc_Id INT NOT NULL,
Ord_Id INT NOT NULL,
Price float NOT NULL,
Quantity int NULL,
CONSTRAINT fk_ordd_pdc FOREIGN KEY (Pdc_Id) REFERENCES Products (Id),
CONSTRAINT fk_ordd_ord FOREIGN KEY (Ord_Id) REFERENCES Orders (Id)
)